---
tenants:
  - name: S1_FABRIC
    mac_vrf_vni_base: 10000
    vrfs:
      - name: OVERLAY
        vrf_vni: 10
        svis:
          - id: 10
            name: 'Ten'
            enabled: true
            ip_address_virtual: 10.10.10.1/24
          - id: 20
            name: 'Twenty'
            enabled: true
            ip_address_virtual: 10.20.20.1/24
            nodes:
            - node: s1-spine1
              ip_address: 10.20.20.2/24
              - node: s1-spine2 # <- Should not be nested under s1-spine1
                ip_address: 10.20.20.3/24


          - id: 30
            name: 'Thiry'
            enabled: true
            ip_address_virtual: 10.30.30.1/24
